[advisories]
version = 2

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib", "Unicode-3.0", "MPL-2.0", "CDDL-1.0", "IJG", "CDLA-Permissive-2.0", "Unicode-DFS-2016", "OpenSSL", "BSL-1.0", "0BSD"]

[[licenses.exceptions]]
allow = ["LGPL-2.1-only", "LGPL-2.1-or-later"]
name = "lcms2"

[bans]
multiple-versions = "warn"
wildcards = "allow"
[[bans.deny]]
name = "jpegxl-rs"
[[bans.deny]]
name = "jpegxl-sys"
[[bans.deny]]
name = "libraw-sys"
