#!/usr/bin/env python3
"""Builds benchmark-results.md from the before/after logs in this directory."""
import re
from pathlib import Path

here = Path(__file__).parent
FIXTURES = ["nef", "cr3", "raf", "arw", "dng"]  # order of the Develop bench runs


def interactive(path):
    rows = {}
    for line in (here / path).read_text().splitlines():
        m = re.match(r"INTERACTIVE_BENCH fixture=(\S+) level=(\d+) op=(\S+) path=(\S+) p50_ms=([\d.]+) p90_ms=([\d.]+)", line)
        if m:
            f, lvl, op, p, p50, p90 = m.groups()
            rows[(f, int(lvl), op)] = (p, float(p50), float(p90))
    return rows


def develop(path, pattern):
    out, fixture = {}, -1
    for line in (here / path).read_text().splitlines():
        if re.match(r"Metal .*(panels|loupe)", line):
            fixture += 1
            continue
        m = re.match(pattern, line)
        if m and fixture >= 0:
            out[(FIXTURES[fixture], m.group(1).strip())] = m.groups()[1:]
    return out


def table_interactive(level):
    before = interactive(f"bench-before-L{level}.log")
    after = interactive(f"bench-after-L{level}.log")
    lines = [
        f"### Level {level} (whole frame, resident surface frame; `path=tiles` = non-resident fallback)",
        "",
        "| Fixture | Operator | Before p50 / p90 ms (path) | After p50 / p90 ms (path) | Speedup (p50) |",
        "|---|---|---:|---:|---:|",
    ]
    for key in sorted(set(before) | set(after)):
        f, _, op = key
        b, a = before.get(key), after.get(key)
        fmt = lambda r: f"{r[1]:.2f} / {r[2]:.2f} ({r[0]})" if r else "n/a"
        speed = f"{b[1] / a[1]:.1f}x" if a and b else ""
        lines.append(f"| {f} | {op} | {fmt(b)} | {fmt(a)} | {speed} |")
    return "\n".join(lines)


def table_develop(name, pattern, header):
    before = develop(f"{name}-before.log", pattern)
    after = develop(f"{name}-after.log", pattern)
    lines = [header, "|---|---|---:|---:|"]
    for key in sorted(set(before) | set(after), key=lambda k: (FIXTURES.index(k[0]), k[1])):
        b, a = before.get(key), after.get(key)
        lines.append(f"| {key[0]} | {key[1]} | {' '.join(b) if b else 'n/a'} | {' '.join(a) if a else 'n/a'} |")
    return "\n".join(lines)


panel = r"\s+(.+?)\s+(L\d+): median ([\d.]+) ms, p90 ([\d.]+) ms"
loupe = r"\s+(.+?)\s+1:1 1024²: cold pan median ([\d.]+) ms, p90 ([\d.]+) ms; edit median ([\d.]+) ms, p90 ([\d.]+) ms"
doc = [
    "# M2-17b benchmark results",
    "",
    "Apple M4 (10-core GPU, 24 GB). Other work packages were building and testing",
    "concurrently (load average 10–35), so absolute numbers carry noise; the",
    "before/after runs used identical harnesses. Before = `5dd1e69` (baseline",
    "worktree), after = this package. Generated by `compare.py`.",
    "",
    "## Per-operator resident frames (`pipeline-gpu/tests/interactive_performance.rs`)",
    "",
    "Each operator is dragged through 7 values at L2 (2 at L0) after one untimed",
    "frame; a frame is `render_surface` into an IOSurface (4 KiB histogram",
    "readback) or, if not resident-capable, the tile fallback Develop uses.",
    "",
    table_interactive(2),
    "",
    table_interactive(0),
    "",
    "## Develop session slider latency (`tessera-ffi/tests/develop.rs bench_panel_latency`)",
    "",
    "Interactive drags at the screen level (settings change → frame published);",
    "the level column is where the adaptive policy settled.",
    "",
    table_develop("panel", panel, "| Fixture | Panel | Before (level, p50 ms, p90 ms) | After (level, p50 ms, p90 ms) |"),
    "",
    "## 1:1 refinement (`bench_detail_preview`, 1024² loupe)",
    "",
    table_develop("loupe", loupe, "| Fixture | Edit | Before (cold p50, p90, edit p50, p90 ms) | After (cold p50, p90, edit p50, p90 ms) |"),
    "",
]
(here / "benchmark-results.md").write_text("\n".join(doc))
print("wrote benchmark-results.md")
