[package]
name = "pipeline-cpu"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
engine-api = { path = "../engine-api" }
raw-decode = { path = "../raw-decode" }
lens = { path = "../lens" }
image = { workspace = true }

[dev-dependencies]
png = { workspace = true }
