[package]
name = "image-core"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
engine-api = { path = "../engine-api" }
pipeline-cpu = { path = "../pipeline-cpu" }
raw-decode = { path = "../raw-decode" }
half = { workspace = true }

[dev-dependencies]
jobs = { path = "../jobs" }
