[package]
name = "mask-ai"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
engine-api = { path = "../engine-api" }
pipeline-cpu = { path = "../pipeline-cpu" }
ml-segment = { path = "../ml-segment" }
ml-runtime = { path = "../ml-runtime" }
image = { workspace = true }
anyhow = { workspace = true }
