// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(CTesseraFFI)
import CTesseraFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tessera_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tessera_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTesseraFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol EngineProtocol: AnyObject, Sendable {
    
    /**
     * RAW cache misses return pending immediately; PreviewReady signals completion.
     */
    func embeddedPreview(imageId: String, maxPx: UInt32) throws  -> PreviewResponse
    
    func getRecipe(imageId: String) throws  -> String
    
    func indexFolder(path: String) throws  -> FolderHandle
    
    func listImages(query: ImageQuery) throws  -> [ImageSummary]
    
    func setEventListener(listener: EngineEventListener?) 
    
    func setRecipeJson(imageId: String, json: String) throws 
    
    func setSelection(imageId: String, selection: Selection) throws 
    
}
open class Engine: EngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tessera_ffi_fn_clone_engine(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_tessera_ffi_fn_free_engine(handle, $0) }
    }

    
public static func `open`(appSupportDir: String)throws  -> Engine  {
    return try  FfiConverterTypeEngine_lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_constructor_engine_open(
        FfiConverterString.lower(appSupportDir),uniffiCallStatus
    )
})
}
    

    
    /**
     * RAW cache misses return pending immediately; PreviewReady signals completion.
     */
open func embeddedPreview(imageId: String, maxPx: UInt32)throws  -> PreviewResponse  {
    return try  FfiConverterTypePreviewResponse_lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_embedded_preview(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(imageId),
        FfiConverterUInt32.lower(maxPx),uniffiCallStatus
    )
})
}
    
open func getRecipe(imageId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_get_recipe(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(imageId),uniffiCallStatus
    )
})
}
    
open func indexFolder(path: String)throws  -> FolderHandle  {
    return try  FfiConverterTypeFolderHandle_lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_index_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
    
open func listImages(query: ImageQuery)throws  -> [ImageSummary]  {
    return try  FfiConverterSequenceTypeImageSummary.lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_list_images(
            self.uniffiCloneHandle(),
        FfiConverterTypeImageQuery_lower(query),uniffiCallStatus
    )
})
}
    
open func setEventListener(listener: EngineEventListener?)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_set_event_listener(
            self.uniffiCloneHandle(),
        FfiConverterOptionTypeEngineEventListener.lower(listener),uniffiCallStatus
    )
}
}
    
open func setRecipeJson(imageId: String, json: String)throws   {try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_set_recipe_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(imageId),
        FfiConverterString.lower(json),uniffiCallStatus
    )
}
}
    
open func setSelection(imageId: String, selection: Selection)throws   {try rustCallWithError(FfiConverterTypeBridgeError_lift) {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engine_set_selection(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(imageId),
        FfiConverterTypeSelection_lower(selection),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Engine

    public static func lift(_ handle: UInt64) throws -> Engine {
        return Engine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Engine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Engine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Engine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngine_lift(_ handle: UInt64) throws -> Engine {
    return try FfiConverterTypeEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngine_lower(_ value: Engine) -> UInt64 {
    return FfiConverterTypeEngine.lower(value)
}






/**
 * Called on the command's worker thread, never while holding a catalog lock.
 */
public protocol EngineEventListener: AnyObject, Sendable {
    
    func onEvent(event: EngineEvent) 
    
}
/**
 * Called on the command's worker thread, never while holding a catalog lock.
 */
open class EngineEventListenerImpl: EngineEventListener, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tessera_ffi_fn_clone_engineeventlistener(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_tessera_ffi_fn_free_engineeventlistener(handle, $0) }
    }

    

    
open func onEvent(event: EngineEvent)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_tessera_ffi_fn_method_engineeventlistener_on_event(
            self.uniffiCloneHandle(),
        FfiConverterTypeEngineEvent_lower(event),uniffiCallStatus
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEngineEventListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceEngineEventListener = UniffiVTableCallbackInterfaceEngineEventListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeEngineEventListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EngineEventListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeEngineEventListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EngineEventListener: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEngineEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeEngineEvent_lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceEngineEventListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceEngineEventListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitEngineEventListener() {
    uniffi_tessera_ffi_fn_init_callback_vtable_engineeventlistener(UniffiCallbackInterfaceEngineEventListener.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineEventListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<EngineEventListener>()

    typealias FfiType = UInt64
    typealias SwiftType = EngineEventListener

    public static func lift(_ handle: UInt64) throws -> EngineEventListener {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return EngineEventListenerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: EngineEventListener) -> UInt64 {
         if let rustImpl = value as? EngineEventListenerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineEventListener {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: EngineEventListener, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineEventListener_lift(_ handle: UInt64) throws -> EngineEventListener {
    return try FfiConverterTypeEngineEventListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineEventListener_lower(_ value: EngineEventListener) -> UInt64 {
    return FfiConverterTypeEngineEventListener.lower(value)
}




public struct FolderHandle: Equatable, Hashable {
    public var path: String
    public var updated: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, updated: UInt64) {
        self.path = path
        self.updated = updated
    }

    

    
}

#if compiler(>=6)
extension FolderHandle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFolderHandle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FolderHandle {
        return
            try FolderHandle(
                path: FfiConverterString.read(from: &buf), 
                updated: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FolderHandle, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterUInt64.write(value.updated, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFolderHandle_lift(_ buf: RustBuffer) throws -> FolderHandle {
    return try FfiConverterTypeFolderHandle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFolderHandle_lower(_ value: FolderHandle) -> RustBuffer {
    return FfiConverterTypeFolderHandle.lower(value)
}


public struct ImageQuery: Equatable, Hashable {
    public var folder: String?
    public var text: String?
    public var decision: Decision?
    /**
     * Zero means all matching rows. Offset is applied before returning them.
     */
    public var limit: UInt32
    public var offset: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(folder: String?, text: String?, decision: Decision?, 
        /**
         * Zero means all matching rows. Offset is applied before returning them.
         */limit: UInt32, offset: UInt32) {
        self.folder = folder
        self.text = text
        self.decision = decision
        self.limit = limit
        self.offset = offset
    }

    

    
}

#if compiler(>=6)
extension ImageQuery: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageQuery: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageQuery {
        return
            try ImageQuery(
                folder: FfiConverterOptionString.read(from: &buf), 
                text: FfiConverterOptionString.read(from: &buf), 
                decision: FfiConverterOptionTypeDecision.read(from: &buf), 
                limit: FfiConverterUInt32.read(from: &buf), 
                offset: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ImageQuery, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.folder, into: &buf)
        FfiConverterOptionString.write(value.text, into: &buf)
        FfiConverterOptionTypeDecision.write(value.decision, into: &buf)
        FfiConverterUInt32.write(value.limit, into: &buf)
        FfiConverterUInt32.write(value.offset, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageQuery_lift(_ buf: RustBuffer) throws -> ImageQuery {
    return try FfiConverterTypeImageQuery.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageQuery_lower(_ value: ImageQuery) -> RustBuffer {
    return FfiConverterTypeImageQuery.lower(value)
}


public struct ImageSummary: Equatable, Hashable {
    public var id: String
    public var path: String
    /**
     * RAW: Unix seconds; EXIF JPEG/TIFF: ISO local date-time without a timezone.
     */
    public var captureTime: String?
    public var orientation: UInt16
    public var selection: Selection
    public var recipeHash: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, path: String, 
        /**
         * RAW: Unix seconds; EXIF JPEG/TIFF: ISO local date-time without a timezone.
         */captureTime: String?, orientation: UInt16, selection: Selection, recipeHash: String) {
        self.id = id
        self.path = path
        self.captureTime = captureTime
        self.orientation = orientation
        self.selection = selection
        self.recipeHash = recipeHash
    }

    

    
}

#if compiler(>=6)
extension ImageSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageSummary {
        return
            try ImageSummary(
                id: FfiConverterString.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                captureTime: FfiConverterOptionString.read(from: &buf), 
                orientation: FfiConverterUInt16.read(from: &buf), 
                selection: FfiConverterTypeSelection.read(from: &buf), 
                recipeHash: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ImageSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.captureTime, into: &buf)
        FfiConverterUInt16.write(value.orientation, into: &buf)
        FfiConverterTypeSelection.write(value.selection, into: &buf)
        FfiConverterString.write(value.recipeHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageSummary_lift(_ buf: RustBuffer) throws -> ImageSummary {
    return try FfiConverterTypeImageSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageSummary_lower(_ value: ImageSummary) -> RustBuffer {
    return FfiConverterTypeImageSummary.lower(value)
}


public struct PreviewResponse: Equatable, Hashable {
    public var bytes: Data?
    public var pending: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data?, pending: Bool) {
        self.bytes = bytes
        self.pending = pending
    }
}

#if compiler(>=6)
extension PreviewResponse: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreviewResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreviewResponse {
        return
            try PreviewResponse(
                bytes: FfiConverterOptionData.read(from: &buf),
                pending: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PreviewResponse, into buf: inout [UInt8]) {
        FfiConverterOptionData.write(value.bytes, into: &buf)
        FfiConverterBool.write(value.pending, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreviewResponse_lift(_ buf: RustBuffer) throws -> PreviewResponse {
    return try FfiConverterTypePreviewResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreviewResponse_lower(_ value: PreviewResponse) -> RustBuffer {
    return FfiConverterTypePreviewResponse.lower(value)
}


public struct Selection: Equatable, Hashable {
    public var decision: Decision
    public var grade: UInt8?
    public var mark: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(decision: Decision, grade: UInt8?, mark: String?) {
        self.decision = decision
        self.grade = grade
        self.mark = mark
    }

    

    
}

#if compiler(>=6)
extension Selection: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSelection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Selection {
        return
            try Selection(
                decision: FfiConverterTypeDecision.read(from: &buf), 
                grade: FfiConverterOptionUInt8.read(from: &buf), 
                mark: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Selection, into buf: inout [UInt8]) {
        FfiConverterTypeDecision.write(value.decision, into: &buf)
        FfiConverterOptionUInt8.write(value.grade, into: &buf)
        FfiConverterOptionString.write(value.mark, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelection_lift(_ buf: RustBuffer) throws -> Selection {
    return try FfiConverterTypeSelection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelection_lower(_ value: Selection) -> RustBuffer {
    return FfiConverterTypeSelection.lower(value)
}


public 
enum BridgeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Failure(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension BridgeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBridgeError: FfiConverterRustBuffer {
    typealias SwiftType = BridgeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failure(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Failure(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBridgeError_lift(_ buf: RustBuffer) throws -> BridgeError {
    return try FfiConverterTypeBridgeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBridgeError_lower(_ value: BridgeError) -> RustBuffer {
    return FfiConverterTypeBridgeError.lower(value)
}



public enum Decision: Equatable, Hashable {
    
    case undecided
    case reject
    case keep





}

#if compiler(>=6)
extension Decision: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecision: FfiConverterRustBuffer {
    typealias SwiftType = Decision

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Decision {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .undecided
        
        case 2: return .reject
        
        case 3: return .keep
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Decision, into buf: inout [UInt8]) {
        switch value {
        
        
        case .undecided:
            writeInt(&buf, Int32(1))
        
        
        case .reject:
            writeInt(&buf, Int32(2))
        
        
        case .keep:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecision_lift(_ buf: RustBuffer) throws -> Decision {
    return try FfiConverterTypeDecision.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecision_lower(_ value: Decision) -> RustBuffer {
    return FfiConverterTypeDecision.lower(value)
}




public enum EngineEvent: Equatable, Hashable {
    
    case scanProgress(path: String, updated: UInt64, finished: Bool
    )
    case previewReady(imageId: String, maxPx: UInt32
    )





}

#if compiler(>=6)
extension EngineEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineEvent: FfiConverterRustBuffer {
    typealias SwiftType = EngineEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .scanProgress(path: try FfiConverterString.read(from: &buf), updated: try FfiConverterUInt64.read(from: &buf), finished: try FfiConverterBool.read(from: &buf)
        )
        
        case 2: return .previewReady(imageId: try FfiConverterString.read(from: &buf), maxPx: try FfiConverterUInt32.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .scanProgress(path,updated,finished):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(path, into: &buf)
            FfiConverterUInt64.write(updated, into: &buf)
            FfiConverterBool.write(finished, into: &buf)
            
        
        case let .previewReady(imageId,maxPx):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(imageId, into: &buf)
            FfiConverterUInt32.write(maxPx, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineEvent_lift(_ buf: RustBuffer) throws -> EngineEvent {
    return try FfiConverterTypeEngineEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineEvent_lower(_ value: EngineEvent) -> RustBuffer {
    return FfiConverterTypeEngineEvent.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeEngineEventListener: FfiConverterRustBuffer {
    typealias SwiftType = EngineEventListener?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeEngineEventListener.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeEngineEventListener.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDecision: FfiConverterRustBuffer {
    typealias SwiftType = Decision?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDecision.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDecision.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeImageSummary: FfiConverterRustBuffer {
    typealias SwiftType = [ImageSummary]

    public static func write(_ value: [ImageSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeImageSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ImageSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [ImageSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeImageSummary.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tessera_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_embedded_preview() != 35338) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_get_recipe() != 42736) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_index_folder() != 25419) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_list_images() != 16781) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_set_event_listener() != 35077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_set_recipe_json() != 19443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engine_set_selection() != 50395) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_method_engineeventlistener_on_event() != 36402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tessera_ffi_checksum_constructor_engine_open() != 29039) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEngineEventListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTesseraFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all