[package]
license = "Apache-2.0"
name = "color-mgmt"
version = "0.1.0"
edition = "2021"

[features]
imageio = []

[dependencies]
lcms2.workspace = true
blake3.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-graphics = { version = "0.3.2", default-features = false, features = ["std", "CGColorSpace", "CGDirectDisplay", "CGError"] }
objc2-core-foundation = { version = "0.3.2", default-features = false, features = ["std", "CFData"] }

[dev-dependencies]
tempfile.workspace = true
